# Homework 1

## Precision, variables, and formulae

### 1) Precision limitations

As an illustration of the limitations of double-precision variables, consider a floating-point number $x$.

Use Python to calculate the product $x^{-1}x$. Try the cases x = 49, 51, and 947.

In a couple of these cases the product will not be exactly equal to 1.

Can you find any other cases for x between 90 and 110 for which the product is not exactly 1?

Why do you think the problem occurs for some values of x but not others?

In [7]:
x = 49
(x**-1)*x

0.9999999999999999

In [8]:
x = 51
(x**-1)*x

1.0

In [9]:
x = 947
(x**-1)*x

0.9999999999999999

In [11]:
for x in range (90, 111):
    if (x**-1)*x != 1:
        print(x)

98
103
107


Answer Placeholder

### 2) Temperature conversion

To convert temperature measurements between degrees Celsius (C) and degrees Fahrenheit (F ),

the following equation is used:

$F = \displaystyle\frac 9 5 C + 32$

To apply this equation, eight diﬀerent versions of code are listed below.

Determine which versions will not work correctly, and explain why in each case.

In [14]:
C = 21
F = 9/5*C + 32
F

69.80000000000001

In [15]:
C = 21.0
F = 9/5*C + 32
F

69.80000000000001

In [16]:
C = 21.0
F = (9/5)*C + 32
F

69.80000000000001

In [17]:
C = 21.0
F = 9.0*C/5.0 + 32
F

69.8

In [18]:
C = 21.0
F = 9.*(C/5.0) + 32
F

69.80000000000001

In [19]:
C = 21
F = 9*C/5 + 32
F

69.8

In [20]:
C = 21
F = (1./5)*9*C + 32
F

69.80000000000001

In [21]:
C = 21
F = (1/5)*9*C + 32
F

69.80000000000001

### 3. Your physics problem
Identify the solution to a physics problem that can be written as a combination of variables and mathematical expressions. 

Use an example from one of your current or recent classes.

Solve the problem using Python, by storing the appropriate values into the variables and evaluating the expression(s).



In a region of free space, the electric field at an instant of time is

$\textbf{E} = (80.0\hat{\textbf{i}} + 32.0\hat{\textbf{j}} - 64.0\hat{\textbf{k}})\frac N C$ 

and the magnetic field is 

$\textbf B = (0.200\hat{\textbf{i}} + 0.0800\hat{\textbf{j}} + 0.290\hat{\textbf{k}})\mu T$

a) Show that the two fields are perpendicular to each other

If $\textbf{E} \cdot \textbf{B} = 0$, then $\textbf E \perp \textbf B$

In [38]:
import numpy as np

# Electric field vector
E = np.array([80.0, 32.0, -64.0]) # N/C

# Magnetic field vector
B = np.array([0.200, 0.0800, 0.290]) # micro tesla

B = B * 1e-6 # tesla

if np.dot(E, B) == 0:
    print("E and B are perpendicular")

E and B are perpendicular


b) Determine the Poynting vector for these fields

The Poynting vector is given by

$\textbf S = \frac{1}{\mu_{0}}(\textbf E \times \textbf B)$

where $\mu_{0}$ is the permeability of free space and $\textbf E$ and $\textbf B$ are the electric and magnetic fields, respectively

In [39]:
mu = 4*np.pi*(10**-7) # Tm/A
S = (np.cross(E, B)) / mu # W/m^2
S.round(1)

array([ 11.5, -28.6,   0. ])

$\therefore \textbf S = (11.5\hat{\textbf i} - 28.6\hat{\textbf j}) \frac{W}{m^2}$